version: 2

jobs:
  build-docker-ubuntu-18:
    steps:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: CPU info
          command: cat /proc/cpuinfo
      - run:
          name: Ubuntu packages
          command: |
            apt update && apt install -y apt-utils
            DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends make gcc g++ git file pkg-config wget curl swig netpbm wcslib-dev wcslib-tools zlib1g-dev libbz2-dev libcairo2-dev libcfitsio-dev libcfitsio-bin libgsl-dev libjpeg-dev libnetpbm10-dev libpng-dev python3 python3-dev python3-pip python3-pil python3-tk
            apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      - checkout
      - run:
          name: Make
          command: |
            make
            make py
            make extra
            make test
      - run:
          name: Tests
          command: |
            (cd util && ./test)
            (cd libkd && ./test)
            (cd solver && ./test)
            (cd plot && ./test)
            make install INSTALL_DIR=~/an PYTHON_SCRIPT="/usr/bin/env $PYTHON"
            export PYTHONPATH=${PYTHONPATH}:~/an/lib/python
            (cd /tmp && $PYTHON -c "import astrometry.libkd.spherematch")
            export PATH=${PATH}:~/an/bin
            build-astrometry-index -d 3 -o index-9918.fits -P 18 -S mag -B 0.1 -s 0 -r 1 -I 9918 -M -i demo/tycho2-mag6.fits
            echo -e 'add_path .\ninparallel\nindex index-9918.fits' > 99.cfg
            solve-field --config 99.cfg demo/apod4.jpg  --continue
            tablist demo/apod4.match
            listhead demo/apod4.wcs

workflows:
  version: 2
  build:
    jobs:
      - "build-docker-ubuntu-18"
